### PR TITLE
feat(pager): don't show pager with only one page

### PR DESCRIPTION
**Pull request by Raigen**
Only show the pager when only one page of products is available.

UNITY-1169

### CODE REVIEW

**Comment by depoulo** [comment]
:+1 for `{?list[1]}`. Does that mean we don't need ePages-de/epages-ui#711 at all?

**Comment by Raigen** [comment]
@erikmueller updated

**Comment by erikmueller** [comment]
@katjamueller @vzerwas any opinion?

**Comment by vzerwas** [comment]
@Raigen fine with Erik´s suggestion

**Comment by Raigen** [comment]
@erikmueller did it

**Comment by Raigen** [comment]
@erikmueller rebased

**Pull request merged**
